# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build and publish
      uses: gradle/gradle-build-action@v2.3.3
      with:
        arguments: test build
    - name: Calculate version
      id: version
      run: |
        echo "PROJECT_VERSION=$(./gradlew properties | grep "version:" | awk '{print $2}')" >> $GITHUB_OUTPUT
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: "Release ${{ steps.version.outputs.PROJECT_VERSION }}"
        tag_name: ${{ steps.version.outputs.PROJECT_VERSION }}
        generate_release_notes: true
        files: |
          ./build/libs/*.jar
    
